name: 'ledgerone'
version: '1.0.0'
config-version: 2

profile: 'ledgerone'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  cecl_forecast_horizon_months: 12

models:
  ledgerone:
    staging:
      +materialized: view
      +schema: staging
    marts:
      core:
        +materialized: table
        +schema: marts
      reporting:
        +materialized: table
        +schema: marts
    credit_risk:
      staging:
        +materialized: view
        +schema: staging
      marts:
        +materialized: table
        +schema: marts
